Minor docstring formatting fixes and refactor input argument validation
sunpy/streamtracer pull request #172
Opened 2024-10-03 01:51 UTC by wtbarnes

This PR does two things:

- Fix some of the formatting in the docstrings for `VectorGrid` and `Streamtracer`
- Refactor the input validation on `VectorGrid`. Previously, the validation was done using a mix of some setters and some static validation methods. This refactor moves all of the validation to setter methods.

2024-10-03 14:15 UTC, nabobalis approved these changes, later dismissed

2024-10-14 10:18 UTC, Cadair requested changes
Looks good, just missing a couple of docstrings on properties.

2024-10-14 10:18 UTC, Cadair commented on python/streamtracer/streamline.py
> +    def grid_spacing(self):
All these properties should have docstrings as well :stuck_out_tongue:

2024-10-14 10:18 UTC, Cadair commented on python/streamtracer/streamline.py
> +        self._xs = val
Given the change [here](https://github.com/sunpy/streamtracer/pull/172/files#diff-7a49ca09f01796352cc0e61289b8b299fe4272203de545d5ede0aa9bb9a3e92fR308) shouldn't this be
```suggestion
        self._xs = np.array(val)
```
to maintain consistency?

2024-10-14 20:14 UTC, wtbarnes commented on python/streamtracer/streamline.py
> +        self._xs = val
No, I don't think so. In the change below, I explicitly do not cast this as an array because each streamline can have a different number of points. That's why it's a list of arrays rather than a higher-dimensional array.

2024-10-16 02:08 UTC, wtbarnes commented
I've added docstrings for all the new properties. I'm not sure why the RTD build is failing...

2024-10-16 03:32 UTC, nabobalis commented
Just needs a kick.

2024-10-16 13:27 UTC, Cadair approved these changes

2024-10-16 13:27 UTC, Cadair commented on python/streamtracer/streamline.py
> +        "Physical spacing between grid points along each axis."
```suggestion
        """
        Physical spacing between grid points along each axis.
        """
```

2024-10-16 13:27 UTC, Cadair commented on python/streamtracer/streamline.py
> +        "Three-dimensional vector field through which the streamlines will be traced."
```suggestion
        """
        Three-dimensional vector field through which the streamlines will be traced.
        """
```

2024-10-16 13:27 UTC, Cadair commented on python/streamtracer/streamline.py
> +        "The physical coordinates along each axis of the grid."
```suggestion
        """
        The physical coordinates along each axis of the grid.
        """
```

2024-10-16 13:31 UTC, merged